### ISSUE TITLE
`Number of included blocks proposed by the Flashbots mev-boost relay` is not a great metric long term

### ISSUE THREAD

**Issue by jparyani** [flashbots/flashbots-data-transparency#18]
It will be not a great metric as we get further and further from the merge. As past data accumulates, this number will move slower and slower, and it's confusing putting it at the top, since people will assume this is our **current** proposal rate.

I recommend either removing it, changing it to be limited to the last day/week, or at least including and prioritizing a more current estimate of our proposal rate.

**Comment by elenahoo** [comment]
added the daily proposal rate charts, we could move those above this pie chart?

**Comment by elenahoo** [comment]
Changed this chart to a %, this should make the number looks more different across time.
