### ISSUE TITLE
The most recent hour of data is sometimes wildly inaccurate

### ISSUE THREAD

**Issue by jparyani** [flashbots/flashbots-data-transparency#19]
Specifically in the `% of blocks proposed by the Flashbots mev-boost relay by hour` graph:
The most recent hour is sometimes wildly off (I just saw it say that flashbots landed 80% of blocks), since it's a partial hour. Suggestions: the most recent hour should sum to less than 100% to signify partial data, or we shouldn't include the most recent hour at all

Might also be a problem in `Hourly average block reward of Flashbots mev-boost relay blocks`, although to a lesser extent.

**Comment by elenahoo** [comment]
Fixed this to remove last hour (if hourly chart) and last day (if daily chart) in internal test dashboard and production dashboard.
