### ISSUE TITLE
The "Other" label in `Average proposer block reward by Flashbots relay and Flashbots builder` is very confusing

### ISSUE THREAD

**Issue by jparyani** [flashbots/flashbots-data-transparency#20]
<img width="513" alt="image" src="https://user-images.githubusercontent.com/1595880/190698612-586e3e37-63cc-4a3e-bb13-6d2c97df9b46.png">

What does "Other" mean here. Why is it a separate field but also stacked on Flashbots?

**Comment by elenahoo** [comment]
The explanation has been added to the info icon (i) next to the title. I've made the bar unstacked too, only showing the average of fb-relay; the x-axis labels are also changed.

Let me know if the info icon is fine, or if we should split this chart into 2 or 3 separate charts @jparyani @tkstanczak.

**Comment by damcnuta** [comment]
Do we have the data to split it into 3 charts so mempool is separate from the other relays? 

I would also update the coloring on the Flashbots column to stay consistent with the lime green used throughout. 

My preference would be to roll out 3 distinct groups (Flashbots vs Other vs Mempool) for every graphic displayed.

**Comment by elenahoo** [comment]
We currently don't have the separation flag for other relays and mempool. @taarushv I don't know if it's possible to create this and how long it takes.

Currently it's consistent in the dashboard that grey is Flashbots, lime green is others

**Comment by elenahoo** [comment]
Closing this issue as the chart has been updated, explanations for "other" also added.

**Comment by jparyani** [comment]
lgtm!
