### ISSUE TITLE
Link to etherscan when clicking block number in `Blocks by the Flashbots builder`

### ISSUE THREAD

**Issue by jparyani** [flashbots/flashbots-data-transparency#22]
<img width="394" alt="image" src="https://user-images.githubusercontent.com/1595880/190699162-3045552b-8ab4-45a5-94e1-e5bdae4e565f.png">

**Comment by gheise** [comment]
- [x] Link block numbers to etherscan

**Comment by elenahoo** [comment]
This is done, the block number now links to etherscan @jparyani.
