### ISSUE TITLE
Daily number of blocks proposed from Flashbots Mev-Boost Relay blocks & Percentage of blocks proposed by Flashbots Mev-Boost Relay vs. other by day is redundant

### ISSUE THREAD

**Issue by bertmiller** [flashbots/flashbots-data-transparency#26]
As the title describes, I think these two graphs are redundant in the information they convey. The daily # of blocks proposed from mev-boost relay vs other isn't super helpful because the daily number of blocks stays the same every day (7.1k), so the percentage makes more sense. I was going to propose that we remove the daily number in favor of the percentage, but I see that we already have that below somewhere. Probably don't need both.

**Comment by gheise** [comment]
- [x] Remove Percentage of blocks proposed by Flashbots Mev-Boost Relay vs. other

**Comment by elenahoo** [comment]
The duplicate chart is removed. Issue can be closed
