### ISSUE TITLE
Some content suggestions

### ISSUE THREAD

**Issue by bertmiller** [flashbots/flashbots-data-transparency#27]
- [x] Use MEV-Boost instead of Mev-Boost
- [x] Use "Flashbots" instead of "FB"
- [x] Some charts are missing descriptions
- [x] Some charts have "Date," some have "block_timestamp" and some don't have a x-axis label at all

**Comment by gheise** [comment]
These have all been fixed. Feel free to review, and close the issue once you're satisfied with these changes. note: I changed the bullet points to check marks, so you could follow along with the progress or unmark them in the case you catch a mistake
