### ISSUE TITLE
Remove hourly average block reward of Flashbots MEV-Boost Relay blocks (today)

### ISSUE THREAD

**Issue by bertmiller** [flashbots/flashbots-data-transparency#28]
<img width="722" alt="Screen Shot 2022-09-20 at 12 31 52 PM" src="https://user-images.githubusercontent.com/30010302/191314047-234fc07e-17e7-4681-8bbb-a7e4ae757f73.png">

I don't think this graph adds much. It's too short of a timescale (in my opinion) and it also isn't showing more than 2 hours of data. I'd remove.

**Comment by gheise** [comment]
- [x] Remove hourly average block reward of Flashbots MEV-Boost Relay blocks (today)
