### ISSUE TITLE
Number of included blocks proposed by the Flashbots MEV-Boost Relay graphs

### ISSUE THREAD

**Issue by bertmiller** [flashbots/flashbots-data-transparency#29]
<img width="1441" alt="Screen Shot 2022-09-20 at 12 34 43 PM" src="https://user-images.githubusercontent.com/30010302/191314652-1615bf91-8e85-45d5-a642-8dc3983d7cea.png">

I think the 24hr graph is the most interesting, and beyond that it's most interesting to know how this number changes over time. Can we get the over time graph?

Not mission critical to launch the dashboard with.

**Comment by gheise** [comment]
- [x] Create graph for percentage of blocks proposed by the Flashbots MEV-Boost Relay over time
